// <auto-generated />
using System;
using CenterAuth.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CenterAuth.Repositories.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20240609080414_UpdateUserTypes")]
    partial class UpdateUserTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CenterAuth.Repositories.Authorization.Permissions.Models.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            Type = "/1/"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Staff",
                            Type = "/2/"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Management",
                            Type = "/2/1/"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SiteAdmin",
                            Type = "/2/1/1/"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Director",
                            Type = "/2/1/2/"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Manager",
                            Type = "/2/1/3/"
                        },
                        new
                        {
                            Id = 7,
                            Name = "OperationsManager",
                            Type = "/2/1/4/"
                        },
                        new
                        {
                            Id = 8,
                            Name = "AdministrativeAssistant",
                            Type = "/2/1/5/"
                        },
                        new
                        {
                            Id = 9,
                            Name = "HR",
                            Type = "/2/2/"
                        },
                        new
                        {
                            Id = 10,
                            Name = "ITSupport",
                            Type = "/2/3/"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Finance",
                            Type = "/2/4/"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Architect",
                            Type = "/3/"
                        },
                        new
                        {
                            Id = 13,
                            Name = "SecuritySpecialist",
                            Type = "/4/"
                        },
                        new
                        {
                            Id = 14,
                            Name = "NetworkEngineer",
                            Type = "/5/"
                        },
                        new
                        {
                            Id = 15,
                            Name = "SupportEngineer",
                            Type = "/6/"
                        },
                        new
                        {
                            Id = 16,
                            Name = "ITAdministrator",
                            Type = "/7/"
                        },
                        new
                        {
                            Id = 17,
                            Name = "SME",
                            Type = "/8/"
                        },
                        new
                        {
                            Id = 18,
                            Name = "TeamMember",
                            Type = "/9/"
                        },
                        new
                        {
                            Id = 19,
                            Name = "ProjectManager",
                            Type = "/9/1/"
                        },
                        new
                        {
                            Id = 20,
                            Name = "TeamLead",
                            Type = "/9/2/"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Developer",
                            Type = "/9/3/"
                        },
                        new
                        {
                            Id = 22,
                            Name = "FrontendDeveloper",
                            Type = "/9/3/1/"
                        },
                        new
                        {
                            Id = 23,
                            Name = "BackendDeveloper",
                            Type = "/9/3/2/"
                        },
                        new
                        {
                            Id = 24,
                            Name = "QAEngineer",
                            Type = "/9/4/"
                        },
                        new
                        {
                            Id = 25,
                            Name = "UXDesigner",
                            Type = "/9/5/"
                        },
                        new
                        {
                            Id = 26,
                            Name = "ProductOwner",
                            Type = "/9/6/"
                        },
                        new
                        {
                            Id = 27,
                            Name = "DevOpsEngineer",
                            Type = "/9/7/"
                        },
                        new
                        {
                            Id = 28,
                            Name = "DataScientist",
                            Type = "/9/8/"
                        });
                });

            modelBuilder.Entity("CenterAuth.Repositories.Users.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserTypeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CenterAuth.Repositories.Users.Models.UserEmail", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "Email");

                    b.ToTable("UserEmails");
                });

            modelBuilder.Entity("CenterAuth.Repositories.Users.Models.User", b =>
                {
                    b.HasOne("CenterAuth.Repositories.Authorization.Permissions.Models.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("CenterAuth.Repositories.Users.Models.UserEmail", b =>
                {
                    b.HasOne("CenterAuth.Repositories.Users.Models.User", null)
                        .WithMany("Emails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CenterAuth.Repositories.Users.Models.User", b =>
                {
                    b.Navigation("Emails");
                });
#pragma warning restore 612, 618
        }
    }
}
